server:
  port: ${PORT:8088}

spring:
  rabbitmq:
    host: localhost
  redis:
    host: localhost
    port: 6379
  cloud:
    stream:
      bindings:
        input:
          destination: test
          group: test
          durableSubscription: true
  zipkin:
    host: localhost
    port: 9411
    base-url: http://localhost:9411

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user
  sessions: NEVER
